# Default values for helloworld.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: "dev/helloworld"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "20230116165137"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "helloworld"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: helloworld.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: example-tls
      hosts:
        - helloword.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

env:
  secret:
    PSP_ENCRYPTION_SALT: "42"
    PSP_ENCRYPTION_KEY: "57791d5430d593164082036ad8b29fb157791d5430d593164082036ad8b29fb157791d5430d593164082036ad8b29fb157791d5430d593164082036ad8b29fb1"
    HCHA_URL: "https://vault.service"
    HCHA_PORT: "8443"
    HC_VAULT_TOKEN: "f0533fd9-aa68-fb91-c172-bb2384ee6876"
    HC_VAULT_ACCESSOR: "a78104ff-e958-7870-8267-9f0f6de06d32"

cert-manager:
  namespace: "cert-manager"